export const PLANETS = [
  {
      id: 'sun',
      name: 'Sun',
      emoji: '☀️',
      cat: 'Food & Beverage',
      color: '#ff9d42',
      glow: '#ff9d42',
      texture: 'sun',
      size: 48,
      radius: 0,
      period: 0,
      sub: ['Restaurants', 'Cafés', 'Bakeries', 'Catering'],
      fx: 'food',
      types: [
          'Restaurants', 'Cafés', 'Bakeries', 'Fast Food', 'Fine Dining',
          'Food Trucks', 'Cloud Kitchens', 'Catering Services', 'Juice Bars',
          'Ice Cream Shops', 'Sweet Shops', 'Tea & Coffee Shops',
          'Pizza Stores', 'BBQ & Grill', 'Organic Food Stores'
      ],
      desc: 'Just as the Sun provides energy to every planet, your food business brings people together through unforgettable flavors and experiences.',
      texture: 'gas',
      isSun: true
  }, {
      id: 'mercury',
      name: 'Mercury',
      emoji: '☿',
      cat: 'Logistics',
      color: '#b7bcc6',
      glow: '#b9c2cc',
      size: 28,
      radius: 150,
      period: 22,
      sub: ['Shipping', 'Supply Chain'],
      fx: 'logistics',
      types: ['Courier Service', 'Trucking & Freight', 'Last-mile Delivery', 'Warehousing', 'Cargo Agency'],
      desc: 'The logistics universe powers global trade — from last-mile delivery to freight and warehousing.',
      texture: 'rocky'
  }, {
      id: 'venus',
      name: 'Venus',
      emoji: '♀',
      cat: 'Beauty',
      color: '#eeb5cf',
      glow: '#e8a9c9',
      size: 32,
      radius: 188,
      period: 26,
      sub: ['Salon', 'Skincare', 'Cosmetics'],
      fx: 'beauty',
      types: ['Salon', 'Spa', 'Bridal Studio', 'Makeup Artist', 'Boutique'],
      desc: 'The beauty universe celebrates self-care — salons, spas, bridal studios, and cosmetic brands.',
      texture: 'swirl'
  }, {
      id: 'earth',
      name: 'Earth',
      emoji: '🌏',
      cat: 'Hospitality',
      color: '#3fae7a',
      glow: '#3fae7a',
      size: 34,
      radius: 263,
      period: 34,
      sub: ['Hotels', 'Resorts', 'Homestays'],
      fx: 'hospitality',
      types: ['Hotel', 'Resort', 'Homestay', 'Villa', 'Guest House'],
      desc: 'The hospitality universe welcomes travelers — hotels, resorts, villas, and homestays.',
      texture: 'earth'
  }, {
      id: 'mars',
      name: 'Mars',
      emoji: '♂',
      cat: 'Fitness',
      color: '#e2603f',
      glow: '#e2543a',
      size: 30,
      radius: 300,
      period: 38,
      sub: ['Gym', 'Sports'],
      fx: 'fitness',
      types: ['Gym', 'Yoga Studio', 'Sports Club', 'Martial Arts', 'Wellness Center'],
      desc: 'The fitness universe is about strength and wellness — gyms, yoga, sports clubs, and wellness centers.',
      texture: 'rocky'
  }, {
      id: 'jupiter',
      name: 'Jupiter',
      emoji: '♃',
      cat: 'Finance',
      color: '#deb45f',
      glow: '#d4af37',
      size: 42,
      radius: 338,
      period: 42,
      sub: ['Banking', 'Fintech'],
      fx: 'finance',
      types: ['Financial Services', 'Consultancy', 'Investment Firm', 'Fintech Startup'],
      desc: 'The finance universe manages wealth — banking, fintech, investment, and consultancy.',
      texture: 'gas'
  }, {
      id: 'saturn',
      name: 'Saturn',
      emoji: '🪐',
      cat: 'Construction',
      color: '#d8bd85',
      glow: '#c9a66b',
      size: 38,
      radius: 375,
      period: 46,
      sub: ['Buildings', 'Infrastructure'],
      fx: 'construction',
      ring: true,
      types: ['Builder / Contractor', 'Real Estate Agency', 'Architecture Firm', 'Interior Design'],
      desc: 'The construction universe builds the future — contractors, real estate, architecture, and interiors.',
      texture: 'gas'
  }, {
      id: 'uranus',
      name: 'Uranus',
      emoji: '⛢',
      cat: 'Software',
      color: '#63dcd2',
      glow: '#4fd1c5',
      size: 32,
      radius: 413,
      period: 50,
      sub: ['IT Services', 'SaaS'],
      fx: 'software',
      types: ['Software Agency', 'IT Services', 'SaaS Product', 'Web Dev Studio'],
      desc: 'The software universe powers digital transformation — IT services, SaaS, and web development.',
      texture: 'ice'
  }, {
      id: 'neptune',
      name: 'Neptune',
      emoji: '♆',
      cat: 'Water',
      color: '#3f7cf0',
      glow: '#2f6fed',
      size: 32,
      radius: 450,
      period: 54,
      sub: ['Water Supply', 'Marine'],
      fx: 'water',
      types: ['Water Supply', 'Bottling Plant', 'Purification Service', 'Aquaculture'],
      desc: 'The water universe sustains life — supply, purification, bottling, and aquaculture.',
      texture: 'ice'
  }, {
      id: 'comet',
      name: 'Comet',
      emoji: '☄️',
      cat: 'Freelancers',
      color: '#bda0ee',
      glow: '#b98ce8',
      size: 26,
      radius: 525,
      period: 62,
      sub: ['Creators', 'Designers'],
      fx: 'freelancers',
      types: ['Freelance Designer', 'Content Creator', 'Photographer', 'Consultant'],
      desc: 'The freelancer universe is for independent creators — designers, photographers, and consultants.',
      texture: 'comet'
  }, {
      id: 'galaxy',
      name: 'Galaxy',
      emoji: '🌌',
      cat: 'Enterprise',
      color: '#9c8ef0',
      glow: '#8f7fe8',
      size: 36,
      radius: 563,
      period: 66,
      sub: ['Large Scale', 'Solutions'],
      fx: 'enterprise',
      types: ['Enterprise Group', 'Chain Business', 'Franchise', 'Holding Company'],
      desc: 'The enterprise universe handles large-scale operations — groups, chains, franchises, and holdings.',
      texture: 'galaxy'
  }, {
      id: 'moon',
      name: 'Moon',
      emoji: '🌕',
      cat: 'Satellite',
      color: '#c7cad6',
      glow: '#6fcf97',
      size: 20,
      radius: 80,
      period: 4,
      parent: 'earth',
      sub: ['Orbits Earth'],
      fx: 'healthcare',
      types: ['Lunar Base', 'Space Tourism'],
      desc: 'The Moon orbits Earth — a small but vital companion.',
      texture: 'moon'
  }
];

export const SATELLITE = {
  emoji: '🛰️',
  name: 'Satellite',
  speed: 0.012,
  pathRadius: 320
};

export const EFFECTS = {
  logistics: { type: 'square', color: 'rgba(200,200,210,0.35)' },
  beauty: { type: 'sparkle', color: 'rgba(255,190,225,0.4)' },
  food: { type: 'circle', color: 'rgba(255,160,70,0.4)' },
  hospitality: { type: 'leaf', color: 'rgba(120,200,150,0.35)' },
  fitness: { type: 'spark', color: 'rgba(255,110,70,0.45)' },
  finance: { type: 'coin', color: 'rgba(255,210,90,0.4)' },
  construction: { type: 'square', color: 'rgba(200,170,120,0.35)' },
  software: { type: 'square', color: 'rgba(90,230,210,0.35)' },
  water: { type: 'wave', color: 'rgba(90,170,255,0.4)' },
  freelancers: { type: 'sparkle', color: 'rgba(200,150,240,0.4)' },
  enterprise: { type: 'sparkle', color: 'rgba(200,200,255,0.35)' },
  healthcare: { type: 'circle', color: 'rgba(110,220,150,0.4)' },
};
