# Generated by Django 6.0.8 on 2026-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
