# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
